### ISSUE TITLE
Scenario outline with examples in title

### ISSUE THREAD

**Issue by rKrums** [cucumber/cucumber-ruby#984]
Regarding this: https://github.com/cucumber/cucumber-js/issues/267

Greetings!
Do we have anything similar in ruby? 

> marcfallows commented on Oct 23, 2014
> Hello,
> 
> I would expect to be able to have my scenario outline title have more information by using the examples >within the title itself:
> 
> ```
> Scenario Outline: A <some> step is <result>
>    When a <some> step
>    Then I get <result>
> Examples:
>    | some    | result  |
>    | passing | passed  |
>    | failing | skipped |
> ```
> 
> Then my scenario titles end up very useful:
> `Scenario: A passing step is passed
> Scenario: A failing step is skipped`
> 
> This doesn't seem to be working for me. Is this a supported feature? If not, is it something that I could >assist in having included? Or, is it not expected to work like this?

If not, it would be very useful to have something like this. It would increase the readability of reports with alot of example data.

**Comment by danascheider** [comment]
I really like this idea too, and I also think it's good to try to have some consistency to where features available in one implementation of Cucumber should also be available in others. Would you be able to put together a PR for this, @rKrums? I'd be happy to help out or pair on this.

**Comment by tooky** [comment]
I'm sure we could do this in the compiler in cucumber-core, but I wonder if it will need to go into gherkin's pickles compiler in the long run.

cc @brasmusson @aslakhellesoy

**Comment by brasmusson** [comment]
The gherkin compilers do implement this already, see https://github.com/cucumber/gherkin/blob/master/testdata/good/example_tokens_everywhere.feature and https://github.com/cucumber/gherkin/blob/master/testdata/good/example_tokens_everywhere.feature.pickles.json

**Comment by rKrums** [comment]
@danascheider I'm on a really tight schedule right now, and would not be able to participate. Thank you for offer. I understand, that it's possible to do that already, but have not checked.

**Comment by sharmarahul** [comment]
Any plans of having this feature in the Ruby version?

**Comment by danascheider** [comment]
@sharmarahul This is already possible.

**Comment by brasmusson** [comment]
@danascheider No, this is not possible in Cucumber-Ruby, as it only uses the Gherkin parser and implements its own (AST) compiler (instead of using Gherkins compiler - which did not exist when the compiler in Cucumber-Ruby-Core was implemented).

**Comment by danascheider** [comment]
Ahhh I see. I was actually just wondering about that as I was poking around in that part of the codebase yesterday. That being the case, @sharmarahul, is this something you'd be able to help out with? If not I'll get to it eventually but I can't promise when.

**Comment by xuanzhaopeng** [comment]
Hi, do we have plan to include this feature in 3.0? 

Thanks

**Comment by Githraine** [comment]
+1, we would really like to see this

**Comment by danascheider** [comment]
@xuanzhaopeng This is not slated for the 3.0 release. We may add it at a later time, but it will happen a lot sooner if you, @Githraine, or @sharmarahul are able to help us out with it. If you are, please let us know and we can point you in the right direction as far as implementation.

**Comment by Githraine** [comment]
What would it take to add this in?

**Comment by mattwynne** [comment]
@Githraine somebody needs to focus in on it and implement it! It looks like it's not a priority for anyone on the contributor team, but we'd be happy to support and coach someone who wanted to do the work. Are you interested?

**Comment by Githraine** [comment]
I have not done that before, but I think it would be useful.  Sure, I'll give it a shot.

**Comment by danascheider** [comment]
@apetkova It's definitely still a feature I'd be interested in adding.

**Comment by apetkova** [comment]
Actually, this feature has already been added to master, but is simply not released yet. It looks it was fixed with https://github.com/cucumber/cucumber-ruby/commit/7f43c9533691522899b87a22a700b22ae7ce20bb ; Since I don't see any tests for it, maybe it was a nice "side effect", but definitely works, so I guess this issue can be resolved?

**Comment by danascheider** [comment]
@apetkova Sounds good. Feel free to reopen/ask us to reopen if it turns out not to be resolved or there's a problem.

**Comment by Githraine** [comment]
We finally got upgraded to the latest Cuke.
This is NOT resolved.  Given this scenario outline:
  @mm_calc_tvr_001 @wip
  Scenario Outline: Traditional vs Roth Base tests - <title>
    Given I output "<title>"
      And I am on the "Traditional vs Roth Calculator" calculator page
    When I populate the calculator from "<inputs>" and "calculate"
    Then the calculator results should match the "base" section of "<inputs>"

    Examples:
      | title                                                  | inputs                                         |
      | Single Higher Roth Now Matches                         | single_higher_now_roth_matches                 |
      | Married Higher Roth Now Matches                        | married_higher_now_roth_matches                |
      | Married Lower Roth Now Matches                         | married_lower_now_roth_matches                 |
      | Married Lower Roth Later Matches                       | married_lower_later_roth_matches               |
      | Married Lower 401k Later Matches                       | married_lower_later_401k_matches               |
      | Single Lower Roth Later Matches                        | single_lower_later_roth_matches                |
      | Married Lower 401k Later no Match                      | married_lower_later_401k_does_not_match        |
      | Single Lower Later 401k no match                       | single_lower_later_401k_does_not_match         |
 the results are showing:
Feature: Calculators - Traditional Vs Roth, Scenario: Traditional vs Roth Base tests - <title>, Examples (#1)

**Comment by sridharUpputuri** [comment]
> @Githraine somebody needs to focus in on it and implement it! It looks like it's not a priority for anyone on the contributor team, but we'd be happy to support and coach someone who wanted to do the work. Are you interested?

Hey seems to be this issue is not at resolved. I was able to implement the solution by overriding the builder class in my local repo. Can you please guide me how to make this change implemented here, so that it helps others.

**Comment by luke-hill** [comment]
So you need to clone the repo (after forking it to your own repo). And then push a branch up and make a Pull Request.

There are a few of us actively supporting the cucumber-ruby project, so it'll get reviewed reasonably quickly.
